### ISSUE TITLE
CopyMessags and ForwardMessages MessageIds field type confussion

### ISSUE THREAD

**Issue by HedgehogNSK** [RxTelegram/RxTelegram.Bot#44]
[Copy Messages documentation](https://core.telegram.org/bots/api#copymessages)  says:

> message_ids | Array of Integer

But in `CopyMessages.cs` the field is of type `List<long>`
```cs
public class CopyMessages : BaseRequest{
...  
  // Summary:
  //     Identifiers of 1-100 messages in the chat from_chat_id to copy. The identifiers
  //     must be specified in a strictly increasing order.
  public List<long> MessageIds { get; set; }
...}
```
The same for `ForwardMessages`:
```cs
public class ForwardMessages : BaseRequest
{...
  // Summary:
  //     Identifiers of 1-100 messages in the chat from_chat_id to forward. The identifiers
  //     must be specified in a strictly increasing order.
  public List<long> MessageIds { get; set; }
```

It's not a big problem, but every other class in the library defines `MessageId` as `int`.
Examples:
```cs
public class Message
{
...
  // Summary:
  //     Unique message identifier
  public int MessageId { get; set; }
  ...
  }
public class CopyMessage : BaseSend, IProtectContent
  //
  // Summary:
  //     Message identifier in the chat specified in from_chat_id
  public int MessageId { get; set; }
 ...}
```

It's an issue for me because in my bot I send an instance of `CopyMessage` from one chat to another, then I send service `Message` and then I tansform the result of this 2 operations into array of message ids which I try to broadcast as a `CopyMessages`. Therefore I have to transform `List<int>` -> `List<long>`. As I said before, it's not a big problem, but it confuses.

Also I'd like to notice that `Observable.ToList` returns `IList<T>` rather then `List<T>`. That's why I'm asking please consider change `MessageIds` field type from `List<long>` to `IList<int>` :)

**Comment by niklasweimann** [comment]
Nice catch, I will try to address this issue in the next release. I think the best thing to do is to update all ID values to long as Telegram already has 52bit Numbers for hier ChatIds/UserIds and they will most likely update to 52bit Numbers everywhere.

For now you should be fine with casting the numbers.

Maybe we can also create Structs for each ID Type so users can not accidentally mix up MessageIds and UserIds... 🤔 What do you think about such a Feature @HedgehogNSK?

**Comment by HedgehogNSK** [comment]
I'm not sure if the intention to change code in order to predict future Telegram API changes is a good idea. 
I doubt that they would do that, because message id is a serial number in a certain chat. Therefore, I can hardly imagine that any chat will contain 2,147,483,647 messages in the near future . But yeah, it's still possible.

But if you wish to go this way, it probably  make sense to consider changing the use a specific type of message id to its wrapper `MessageIdObject` which is in the library already . 
For instance,
```cs
  public Task<MessageIdObject> CopyMessage(CopyMessage copyMessage
        , CancellationToken cancellationToken = default(CancellationToken))
  ```

* The benefit of this approach will be unified interface for work with `MessageIdObject`. Like `ChatId` that is already used  in similar way.
* The drawback is that a program have to pay extra time and memory to create and manage the wrappers. To reduce the impact of this disadvantages `MessageIdObject` can be switched from class to structure or record,
